# Site settings
title: 0's and 1's!
header-img: img/hacker-bg.jpg
email: kharekartik@gmail.com

name: 'Kartik Khare'
author: 'Kartik Khare'
author_image: "/img/author.jpg"

description: "The bits of my life."
baseurl: ""
url: "http://kkcorps.github.io"
linkedin_username: kartik-khare/7a/68b/751
twitter_username: KKcorps
github_username:  KKcorps
facebook_username: KK.corps
quora_username: Kartik-Khare

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about
 - title: Projects
   url: /projects


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
