# Site settings
title: The Underdog Dev!
header-img: img/hacker.jpg
email: kharekartik@gmail.com

name: 'Kartik Khare'
author: 'Kartik Khare'
author_image: "/img/author.jpg"

description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://kkcorps.github.io"
twitter_username: KKcorps
github_username:  KKcorps
facebook_username:  Kartik Khare

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
